# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Brett Harris
title: Senior Network System Administrator
email: brett.h@email.co.uk
website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Siam Commercial Bank (SCB)
        sub_title: Software Engineer
        caption: Jan 2023 - Present | Bangkok, Thailand
        description: |
          **Project: Electronic Presentment and Payment (EPPD) System**
          - Developed and maintained banking applications using Java, Spring Boot, Kafka, and microservices.
          - Optimized performance and improved security of critical backend services.
          - Collaborated with cross-functional teams to support Dev, SIT, UAT, and Production environments.
          - Implemented logging and monitoring solutions to enhance system reliability.
      - layout: left
        title: Hitachi Vantara (Thailand) Ltd.
        sub_title: Full Stack Developer
        caption: Jan 2022 - Jan 2023 | Bangkok, Thailand
        description: |
          **Project: Electronic Presentment and Payment (EPPD) System**
          - Built and maintained backend services for an electronic presentment and payment (EPPD) system.
          - Worked in event-driven architecture using Kafka.
          - Developed microservices under Agile methodology.
          - Designed and implemented secure authentication and authorization mechanisms.
      - layout: left
        title: Azure Computers Thailand
        sub_title: Full Stack Developer
        caption: Jan 2021 - Jan 2022 | Bangkok, Thailand
        description: |
          **Project: ME by TTB (Mobile App & Web)**
          - Provided hotfixes and change requests for Internet Banking applications.
          - Built mobile applications using Ionic 1, Cordova, Xcode 11.
          - Troubleshoot and resolved production issues effectively.

          **Project: TTB Touch**
          - Developed and maintained backend services using Kony.
          - Worked closely with Business Analysts (BA) to refine business requirements.

      - layout: left
        title: Allianz Technology Thailand
        sub_title: Backend Developer
        caption: July 2019 - Jan 2021 | Bangkok, Thailand
        description: |
          **Project: Individual Life Belgium (Insurance System)**
          - Built an internal web application for insurance brokers in Germany.
          - Developed frontend with Angular 7 and Ngrx (Redux state management).
          - Implemented backend using Java 8-11, Spring Boot (microservices architecture).
          - Participated in Agile Scrum team, collaborating closely with QA and Business Units.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
